---
- name: INSTALL | Ensure GUFW is installed
  ansible.builtin.apt:
    name: gufw
    state: latest
  become: true
  
- name: CONFIGURE | Allow related and established connections
  community.general.ufw:
    rule: allow
    direction: in
    proto: tcp
    src: 172.16.10.0/24
    from_port: 993
  become: yes
