---
 - name: INSTALL | Ensure snmp tools are installed from apt repository
   become: True
   ansible.builtin.apt:
     pkg:
     - libsnmp-dev
     - snmp
     - snmpd
     state: latest
   when: ansible_facts['os_family'] == "Debian"
