---
 - name: INSTALL | Ensure SNMP tools are installed from apt repository
   become: true
   ansible.builtin.apt:
     pkg:
     - libsnmp-dev
     - snmp
     - snmpd
     state: latest
   when: ansible_facts['os_family'] == "Debian"
   notify: Stop SNMP service

 - name: Flush handlers
   meta: flush_handlers

 - name: CONFIGURE | Ensure SNMP user is created
   become: true
   ansible.builtin.command:
    cmd: net-snmp-config --create-snmpv3-user -ro -A {{ auth_password }} -X {{ encryption_password }} -a {{ auth_algorithm }} -x {{ crypto_algorithm }} {{ auth_username }}
...
