---
- name: CONFIGURE | Ensure background is on remote computer
  ansible.builtin.copy:
    src: cat_wallpaper.jpeg
    dest: /usr/share/backgrounds/cat_wallpaper.jpeg
  become: true

- name: INSTALL | Ensure python pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true

- name: INSTALL | Ensure psutil is installed via pip
  ansible.builtin.pip:
    name: psutil

- name: CONFIGURE | Ensure desktop background is company brand
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/cat_wallpaper.jpeg'"
    state: present
...
