---
- name: CONFIGURE | Ensure background is on remote computer
  ansible.builtin.copy:
    src: cat_wallpaper.jpeg
    dest: /usr/share/backgrounds/cat_wallpaper.jpeg
  become: true

- name: INSTALL | Ensure python pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true

- name: INSTALL | Ensure psutil is installed via pip
  ansible.builtin.pip:
    name: psutil
  become: true

- name: CONFIGURE | Ensure /etc/dconf/profile/user is correct
  ansible.builtin.copy:
    src: user
    dest: /etc/dconf/profile/user
  become: true
  
- name: CONFIGURE | Ensure /etc/dconf/db/local.d exists
  ansible.builtin.file:
    dest: /etc/dconf/db/local.d
    state: directory
  become: true
  
- name: CONFIGURE | Ensure /etc/dconf/db/local.d/01-background is correct
  ansible.builtin.template:
    src: 01-background
    dest: /etc/dconf/db/local.d/01-background
  become: true
  notify: Update dconf

- name: CONFIGURE | Ensure /etc/dconf/profile/gdm is correct
  ansible.builtin.copy:
    src: gdm
    dest: /etc/dconf/profile/gdm
  become: true
  
- name: CONFIGURE | Ensure /etc/dconf/db/gdm.d exists
  ansible.builtin.file:
    dest: /etc/dconf/db/gdm.d
    state: directory
  become: true

- name: CONFIGURE | Ensure /etc/dconf/db/gdm.d/01-banner-message is correct
  ansible.builtin.template:
    src: 01-banner-message
    dest: /etc/dconf/db/gdm.d/01-banner-message
  become: true
  notify: Update dconf
  
- name: CONFIGURE | Ensure /etc/dconf/db/gdm.d/01-logo is correct
  ansible.builtin.template:
    src: 01-logo
    dest: /etc/dconf/db/gdm.d/01-logo
  become: true
  notify: Update dconf

# NOTE: Changing desktop doesn't seem to work
# NOTE: Modifying dconf only modifies it for the ansible user by default
#- name: CONFIGURE | Ensure desktop background is company brand
#  community.general.dconf:
#    key: "/org/gnome/desktop/background/picture-uri"
#    value: "'file:///usr/share/backgrounds/cat_wallpaper.jpeg'"
#    state: present
...
