---
- name: CONFIGURE | Ensure background is on remote computer
  ansible.builtin.copy:
    src: cat_wallpaper.jpeg
    dest: /usr/share/backgrounds/
    
- name: CONFIGURE | Ensure desktop background is company brand
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: /usr/share/backgrounds/cat_wallpaper.jpeg
    state: present
...
